apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: wavefront-collector-psp
rules:
  - apiGroups:
    - policy
    resourceNames:
    - wavefront-collector-psp
    resources:
    - podsecuritypolicies
    verbs:
    - use

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wavefront-collector-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wavefront-collector-psp
subjects:
- kind: ServiceAccount
  name: wavefront-collector
  namespace: wavefront
